### ISSUE TITLE
WindowedLimit with configurable percentile in addition to average

### ISSUE THREAD

**Issue by IgorPerikov** [Netflix/concurrency-limits#106]
I've been thinking how a perfect installation of concurrency-limits might look like for my needs. I walked along the path `Vegas` -> `Gradient2` -> `AIMD` -> `AIMD` wrapped with `Windowed`. And it gave me an idea that calculating average response times usually less representative for real-time services, even if average would've been a perfect p50, I'd like to have my limits reduced earlier than the time when half of my users are out of acceptable timings. What people usually monitor is percentiles like p90, p95, p99, p999, and that's the metric I would prefer to have for my AIMDLimit, because it's a better representation for users experience. So I think concurrency-limits would be a better tool, if it has a percentile-window support. 

I've made some research according to moving percentile algorithms and it seems like the only O(1) algorithm described [here](http://mjambon.com/2016-07-23-moving-percentile/) and it requires some knowledge about time distribution and it might be less accurate in some cases (check out the plot at the bottom of the article), also it's less straightforward, therefore it's more error-prone and harder to trust in. 

I'd like to help with that, if team doesn't mind and I think that `O(N)` space, `O(logN)` insert time, `O(1)` percentile calculation implementation might be an appropriate solution here. My idea for now looks like this:
1. Allow `WindowedLimit` to work with abstractions other than `ImmutableSampleWindow`. 
2. Write some sort of `PercentileSampleWindow` class which is mutable (I think copying N observations on each sample is too much) which will be backed with `PriorityBlockingQueue`
3. When window is ready - fetch queue-backing array with reflection (to avoid extra copies), get `size()*percentile` value, call `onSample()` and update the `WindowedLimit`'s field with a brand new instance of `PercentileSampleWindow`.

What do you think so far?

**Comment by IgorPerikov** [comment]
@elandau Would you mind providing any advises?

**Comment by elandau** [comment]
@IgorPerikov Glad to see people jumping in with suggestions for improvement. I'm big fan of percentiles as they are definitely better than averages for analyzing system performance. However, traditional congestion control algorithms are really more interested in jut identifying latency trends.  In fact, most algorithms prefer to use minimum latency measurements and not averages.  I chose averages as they are very easy to calculate, both space and time, and are less prone to random low latency measurements (think things like heartbeats) resulting in a non-realistic minimum (no load) RTT.  With that said, I definitely think percentiles give a much better representation of a system's latency profile and eliminate the impact of outliers.  50th percentile is probably ideal as there are some clever optimizations for tracking it using little memory or cpu and can even be made lock free.  I can also see percentiles feeding into the timeout latency used in AIMD thereby eliminating the need for any configuration.  

My recommendation for moving forward would be to simplify SampleWindow so it tracks a single value as input to the different limiter algorithms (aimd, gradient, ...).  `sum` can be eliminated as it is a metric implementation concern (average, percentile, min) and of no real interest to the limit algorithm.  At first, I'd just recommend doing a naive implementation for PercentileSampleWindow to gauge the efficacy of the approach.  We can optimize the implementation once the use of percentiles have been validated.

**Comment by IgorPerikov** [comment]
> My recommendation for moving forward would be to simplify SampleWindow so it tracks a single value as input to the different limiter algorithms (aimd, gradient, ...). `sum` can be eliminated as it is a metric implementation concern (average, percentile, min) and of no real interest to the limit algorithm. At first, I'd just recommend doing a naive implementation for PercentileSampleWindow to gauge the efficacy of the approach. We can optimize the implementation once the use of percentiles have been validated.

Thanks, it all makes sense. I'll get back with something to show, maybe something intermediate, so we can discuss details in-progress :man_technologist:

**Comment by IgorPerikov** [comment]
I am closing the issue since non-naive implementation https://github.com/Netflix/concurrency-limits/pull/119 is on master, thanks for the support
