### ISSUE TITLE
Question about simulating problems

### ISSUE THREAD

**Issue by adamconnelly** [Netflix/concurrency-limits#117]
I'm starting to investigate creating a .NET library that implements some of the concepts in this library, but the part that I'm struggling with a bit is figuring out how I can simulate some of the issues that the library is meant to protect against (latency spikes, resource exhaustion, etc). Basically I want to make sure that what I'm implementing is actually working as expected and providing a benefit.

I was just wondering if you had any pointers on how to go about simulating or benchmarking to save me reinventing the wheel, or had any links to information you used when designing and implementing this library.

Thanks in advance!

**Comment by guilherme** [comment]
@adamconnelly hi! did you manage to  simulate?

**Comment by adamconnelly** [comment]
@guilherme unfortunately not - it's not been a priority and I haven't had a chance to look at this since. I'd still be interested in knowing good techniques to simulate this though!

**Comment by spockz** [comment]
Latency spikes can be simulated by routing the traffic through a proxy (envoy supports it out of the box and there are many others) or even just on the tcp level with iptables or tc on Linux or throttle/pfctrl on macOS.

Tools such as chaos monkey can be used to simulate resource contention like another process using up all the cpu and ram in a vm. I'm not aware of something doing this in the same JVM process.

**Comment by guilherme** [comment]
Thank you for the hints @spockz I found this video here: https://www.youtube.com/watch?v=CQvmSXlnyeQ you might find interesting @adamconnelly 

It explains how they simulated traffic to implement it on envoy.  They've built a tool for it: https://github.com/tonya11en/bufferbloater

**Comment by guilherme** [comment]
A little more info about this talk: https://twitter.com/tonya11en/status/1295762154214195203

**Comment by adamconnelly** [comment]
@guilherme thanks for sharing that - the talk was really interesting. It was really cool seeing the graphs from the various test scenarios that were run!
