### ISSUE TITLE
Logic behind dropping AIMD current limit by half when reaching maximum

### ISSUE THREAD

**Issue by IgorPerikov** [Netflix/concurrency-limits#155]
https://github.com/Netflix/concurrency-limits/blob/5ae2be4fea9848af6f63c7b5632af30c494e7373/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/AIMDLimit.java#L102-L104

May anyone describe why is that needed? It looks like if congestion doesn't occur and current limit reached its maximum, it's because maxlimit was pessimistically low, so instead of keep working successfully at full steam, limits will be halved and so the incoming traffic (and redistributing traffic from current instance will bring it to others and potentially hit maximum there and be halved again), which otherwise could've been processed correctly

**Comment by martinlocurcio** [comment]
I have exactly the same question.
Also in low response times I'm having spikes in the value of N due to GC pauses.
https://stackoverflow.com/questions/59311752/how-to-limit-concurrency-in-a-webapp-when-gc-pauses-last-more-than-the-average-r#

**Comment by DieBauer** [comment]
Can this issue be closed as implemented by #174 ?
