### ISSUE TITLE
Rest Client concurrency limiter - Clarification

### ISSUE THREAD

**Issue by banandh** [Netflix/concurrency-limits#188]
Hi - I'm invoking a REST based service from my application using webclient, and would like to use this ConcurrencyLimitServletFilter  in my client to apply backpressure to limit the number of request sent to the server so the server will not get overloaded too much and  client will not wait a long time to get connection failure.

ConcurrencyLimitServletFilter can this filter be used for both client and server concurrency limiting? 

If someone can provide a  Sample of how to register ConcurrencyLimitServletFilter in webclient will be helpful.

**Comment by fedorka** [comment]
Unfortunately, ConcurrencyLimitServletFilter is a servlet filter and is not applicable to Spring Webclient.

We don't currently have project reactor adapters for this library. You may consider using the [bulkhead capability from resilience4j ](https://resilience4j.readme.io/docs/examples-1#decorate-mono-or-flux-with-a-bulkhead).
