### ISSUE TITLE
Queuesize problem in Gradient2Limit

### ISSUE THREAD

**Issue by Jon-Gaara** [Netflix/concurrency-limits#189]
Why does queuesize in Gradient2Limit always return 4 instead of using the square root as written in the "Performance Under Load" article? What's the purpose of doing this?

![1694511328907](https://github.com/Netflix/concurrency-limits/assets/7116647/f30361c3-55f6-49e0-9179-eba0c14d9440)

**Comment by fedorka** [comment]
That paper describes our experience with the original gradient limit. The gradient2 algorithm converges faster than gradient and benefits less from the quick growth. Using a fixed queueSize is simpler so we've left that as the default.

It remains possible to configure the limiter to use the square root function for queue size by passing it via the builder.

**Comment by Jon-Gaara** [comment]
thanks.
