### ISSUE TITLE
Why does Log10RootFunction compute Math.sqrt?

### ISSUE THREAD

**Issue by thekalinga** [Netflix/concurrency-limits#97]
Currently [Log10RootFunction](https://github.com/Netflix/concurrency-limits/blob/b2408be8064d2f94455fee8f0bbe442fc482d9d2/concurrency-limits-core/src/main/java/com/netflix/concurrency/limits/limit/functions/Log10RootFunction.java#L46) has the following code

```java
    @Override
    public Integer apply(Integer t) {
        return t < 1000 ? lookup[t] : (int)Math.sqrt(t);
    }
```

I assume this is a mistake as we are pre computing `log10` for first 1000 number like this

```java
    static {
        IntStream.range(0, 1000).forEach(i -> lookup[i] = Math.max(1, (int)Math.log10(i)));
    }
```

Can you fix this?

**Comment by elandau** [comment]
Fixed with #96
